language: go

go:
  - 1.8
  - 1.9

branches:
  only:
    - "master"

before_install:
  - sudo apt-get install -y inotify-tools

matrix:
  allow_failures:
    - go: tip
  fast_finish: true

os:
  - linux
  - osx

env:
  - GOOS=linux
  - GOOS=darwin

notifications:
  email:
    on_success: never
    on_failure: never