language: go

go:
  - 1.8
  - 1.9
  - tip
  
branches:
  only:
    - "master"

matrix:
  allow_failures:
    - go: tip
  fast_finish: true

notifications:
  email:
    on_success: never
    on_failure: never