language: go

# In theory, older versions would probably work just fine
go:
  - 1.9

branches:
  only:
    - "master"

before_install:
  - sudo apt-get install -y inotify-tools

env:
  - GOOS=linux
  - GOOS=darwin