language: go

go:
  - 1.8
  - 1.9
  - 1.10

branches:
  only:
    - "master"

matrix:
  allow_failures:
    - go: 1.8
    - go: 1.9
    - go: 1.10
  fast_finish: true

env:
  - GOOS=linux
  - GOOS=darwin

script:
  - go get -u -t ./...

notifications:
  email:
    on_success: never
    on_failure: never