language: go

go:
  - 1.9

branches:
  only:
    - "master"

addons:
  apt:
    packages:
    - libgtk2.0-dev
    - xvfb

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gtk+; fi

os:
  - linux
  - osx

env:
  - GOOS=linux
  - GOOS=darwin

notifications:
  email:
    on_success: never
    on_failure: never