language: go

go:
  - 1.7
  - 1.8
  - 1.9.3

branches:
  only:
    - "master"

addons:
  apt:
    packages:
    - libgtk2.0-dev

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gtk+; fi

os:
  - linux
  - osx

env:
  - GOOS=linux
  - GOOS=darwin

notifications:
  email:
    on_success: never
    on_failure: never

ignore:
  - github.com/esimov/diagram/vendor/github.com/fogleman/gg/examples/*