language: go

addons:
  apt_packages:
    - libgl1-mesa-dev
    - xorg-dev

go:
  - 1.8
  - 1.9
  - 1.10.x
  - tip

branches:
  only:
    - "master"

matrix:
  allow_failures:
      - go: tip
  fast_finish: true

env:
  - GOOS=linux
  - GOOS=darwin

script:
  - go get -u -t ./...

notifications:
  email:
    on_success: never
    on_failure: never