language: go

go:
  - 1.9

branches:
  only:
    - "master"

matrix:
  allow_failures:
    - go: 1.8
    - go: 1.9
  fast_finish: true

script:
  - go get -u -t ./...

notifications:
  email:
    on_success: never
    on_failure: never