sudo: false

addons:
  apt_packages:
    - libgl1-mesa-dev
    - xorg-dev

language: go

go:
  - 1.11.x
  - 1.10.x
  - 1.9
  - tip

branches:
  only:
    - "master"

matrix:
  allow_failures:
      - go: tip
  fast_finish: true

script:
  - go get -u -t ./...

notifications:
  email:
    on_success: never
    on_failure: never