language: go

go:
  - 1.8
  - 1.9

branches:
  only:
    - "master"

os:
  - linux
  - osx

matrix:
  allow_failures:
    - go: 1.8
    - go: 1.9
  fast_finish: true

os:
  - linux
  - osx

env:
  - GOOS=linux
  - GOOS=darwin

notifications:
  email:
    on_success: never
    on_failure: never